### ISSUE TITLE
[PE-D][Tester E] Find: unable to find person with no clan and description

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-3/tp#180]
There could be a scenario where the user would like to find a person with no clan and description (such as entry 3). However, this is currently not supported.

![Screenshot 2024-04-05 at 4.50.11 PM.png](https://raw.githubusercontent.com/solomonng2001/ped/main/files/d45b95d1-fb74-41c8-a731-1034d3c8f519.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: solomonng2001/ped#9

**Comment by ChenXy128** [comment]
mention in doc that it is not intended for our app to find anyone with no cat and description.

**Comment by HongRay** [comment]
Throw an error that says both fields cannot be empty.

**Comment by HongRay** [comment]
Ask prof regarding this error.
