### ISSUE TITLE
[PE-D][Tester A] Add command not working as intended

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-3/tp#188]
Should add n/Namet/Tag work the same as add n/Name t/Tag?

![image.png](https://raw.githubusercontent.com/Benson15912/ped/main/files/ee976702-b3f1-4c99-ab10-3a38dd77fea6.png)

![image.png](https://raw.githubusercontent.com/Benson15912/ped/main/files/7afb2cef-ab3c-4346-91fa-d3b1c7e42ca4.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Benson15912/ped#14

**Comment by ChenXy128** [comment]
mention in ug that all prefixes need to be separated with space.
